apiVersion: v1
kind: Pod
metadata:
  name: server-mesher
  labels:
    app: perf
    version: 0.0.1
spec:
  containers:
    - name: server
      image: xiaoliang/server-go
      ports:
        - containerPort: 9999
      resources:
        limits:
          cpu: "1"
    - name: mesher
      image: xiaoliang/mesher
      args:
        - --service-ports
        - rest:9999
      env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CSE_REGISTRY_ADDR
#          value: http://service-center.default:30100
          value: http://192.168.1.94:30100
        - name: SERVICE_PORTS
          value: rest:9999
      ports:
        - containerPort: 30101
        - containerPort: 30102
        - containerPort: 6060
      resources:
          limits:
            cpu: "2"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: service-mesher
spec:
  selector:
    app: perf
  ports:
  - protocol: TCP
    name: mesher
    port: 30105
    nodePort: 30105
    targetPort: 30101
  - protocol: TCP
    name: server
    port: 30104
    nodePort: 30104
    targetPort: 9999
  type: NodePort