version:  '3'
services:
  php-server:
    build: ./server
  php-client:
    build: ./client
    environment:
      http_proxy: http://127.0.0.1:30101
    network_mode: "service:mesher-consumer"
    depends_on:
      - mesher-consumer
  mesher-provider:
    image: medsci/mesher:latest
    environment:
      CSE_REGISTRY_ADDR: http://176.122.130.202:30100
      SPECIFIC_ADDR: 127.0.0.1:80
      SERVICE_NAME: "hellomesher"
    network_mode: "service:php-server"
    depends_on:
      - php-server
  mesher-consumer:
    image: medsci/mesher:latest
    environment:
      CSE_REGISTRY_ADDR: http://176.122.130.202:30100
      SERVICE_NAME: "mesher-consumer"

