version:  '3'
services:
  php-server:
    build: ./server
    container_name: php-server-example
    restart: always  
    networks:      
      - network-php-server  
  php-client:
    build: ./client
    restart: always
    container_name: php-client-example
    environment:
      http_proxy: http://127.0.0.1:30101
    networks:      
     - network-php-client
    depends_on:
      - mesher-consumer
  mesher-provider:
    image: medsci/mesher:latest
    restart: always
    container_name: php-provider-mesher-example
    environment:
      CSE_REGISTRY_ADDR: http://176.122.130.202:30100
      SPECIFIC_ADDR: 127.0.0.1:80
      SERVICE_NAME: "hellomesher"
    networks:      
      - network-php-server
    depends_on:
      - php-server
  mesher-consumer:
    image: medsci/mesher:latest
    restart: always
    container_name: php-consumer-mesher-example
    environment:
      CSE_REGISTRY_ADDR: http://176.122.130.202:30100
      SERVICE_NAME: "mesher-consumer"
    networks:      
      - network-php-server