apiVersion: v1
kind: Pod
metadata:
  name: client-mesher
  labels:
    app: client-mesher
    version: 0.0.1
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - perf
        topologyKey: kubernetes.io/hostname
  containers:
    - name: client
      image: xiaoliang/client-go
      env:
        - name: TARGET
          value: http://server-mesher/
        - name: http_proxy
          value: http://127.0.0.1:30101/
      ports:
        - containerPort: 9000
      resources:
        limits:
          cpu: "0.5"
    - name: mesher
      image: xiaoliang/mesher
      env:
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CSE_REGISTRY_ADDR
#          value: http://service-center.default:30100
          value: http://192.168.1.94:30100
      ports:
        - containerPort: 30101
        - containerPort: 30102
        - containerPort: 6060
      resources:
          limits:
            cpu: "0.5"
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: client-mesher
spec:
  selector:
    app: client-mesher
  ports:
  - protocol: TCP
    name: client
    port: 30107
    nodePort: 30107
    targetPort: 9000
  - protocol: TCP
    name: client-mesher
    port: 30106
    nodePort: 30106
    targetPort: 30101
  type: NodePort